; Language files
!insertmacro MUI_LANGUAGE "Arabic"
!insertmacro MUI_LANGUAGE "Albanian"
!insertmacro MUI_LANGUAGE "Belarusian"
!insertmacro MUI_LANGUAGE "Catalan"
!insertmacro MUI_LANGUAGE "Croatian"
!insertmacro MUI_LANGUAGE "Czech"
!insertmacro MUI_LANGUAGE "Danish"
!insertmacro MUI_LANGUAGE "Dutch"
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Farsi"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "Greek"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "Hungarian"
!insertmacro MUI_LANGUAGE "Indonesian"
!insertmacro MUI_LANGUAGE "Italian"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Lithuanian"
!insertmacro MUI_LANGUAGE "Polish"
!insertmacro MUI_LANGUAGE "Portuguese"
!insertmacro MUI_LANGUAGE "PortugueseBR"
!insertmacro MUI_LANGUAGE "Romanian"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "Spanish"
!insertmacro MUI_LANGUAGE "Swedish"
!insertmacro MUI_LANGUAGE "Thai"
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "Turkish"
!insertmacro MUI_LANGUAGE "Ukrainian"
!insertmacro MUI_RESERVEFILE_LANGDLL

LangString RequireWindows7 ${LANG_ENGLISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_ENGLISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_ENGLISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_ENGLISH} "Localization"
LangString CreateDesktopShortcut ${LANG_ENGLISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_ENGLISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_ENGLISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_ENGLISH} "Show release notes"
LangString AppUninstall ${LANG_ENGLISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_ENGLISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_ENGLISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_ENGLISH} "Close running instances..."
LangString ShortcutHistory ${LANG_ENGLISH} "History"
LangString ShortcutLicense ${LANG_ENGLISH} "License"
LangString ShortcutReadme ${LANG_ENGLISH} "Readme"
LangString ShortcutUninstall ${LANG_ENGLISH} "Uninstall"

LangString RequireWindows7 ${LANG_FRENCH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_FRENCH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_FRENCH} "Core files ${APP_NAME}"
LangString Localization ${LANG_FRENCH} "Localization"
LangString CreateDesktopShortcut ${LANG_FRENCH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_FRENCH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_FRENCH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_FRENCH} "Show release notes"
LangString AppUninstall ${LANG_FRENCH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_FRENCH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_FRENCH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_FRENCH} "Close running instances..."
LangString ShortcutHistory ${LANG_FRENCH} "History"
LangString ShortcutLicense ${LANG_FRENCH} "License"
LangString ShortcutReadme ${LANG_FRENCH} "Readme"
LangString ShortcutUninstall ${LANG_FRENCH} "Uninstall"

LangString RequireWindows7 ${LANG_GERMAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_GERMAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_GERMAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_GERMAN} "Localization"
LangString CreateDesktopShortcut ${LANG_GERMAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_GERMAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_GERMAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_GERMAN} "Show release notes"
LangString AppUninstall ${LANG_GERMAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_GERMAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_GERMAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_GERMAN} "Close running instances..."
LangString ShortcutHistory ${LANG_GERMAN} "History"
LangString ShortcutLicense ${LANG_GERMAN} "License"
LangString ShortcutReadme ${LANG_GERMAN} "Readme"
LangString ShortcutUninstall ${LANG_GERMAN} "Uninstall"

LangString RequireWindows7 ${LANG_ITALIAN} "${APP_NAME} richiede Windows 7 o versione sucecssiva!"
LangString UninstallAp ${LANG_ITALIAN} "Sei sicuro di voler disinstallare ${APP_NAME}?"
LangString CoreFiles ${LANG_ITALIAN} "File principali ${APP_NAME}"
LangString Localization ${LANG_ITALIAN} "Traduzioni"
LangString CreateDesktopShortcut ${LANG_ITALIAN} "Crea collegamento applicazione sul desktop"
LangString CreateStartMenuShortcut ${LANG_ITALIAN} "Crea collegamento nel menu Start"
LangString StoreSettingsApplicationDir ${LANG_ITALIAN} "Salva impostazioni in cartella applicazioni (modo portatile)"
LangString ShowReleaseNote ${LANG_ITALIAN} "Visualizza info sulla nuova versione del programma"
LangString AppUninstall ${LANG_ITALIAN} "Vuoi disinstallare ${APP_NAME}?"
LangString AppRemoved ${LANG_ITALIAN} "${APP_NAME} è stato completamente rimosso!"
LangString AppFolderNotCheck ${LANG_ITALIAN} "Non sembra che ${APP_NAME} sia installato nella cartella di installazione.$\r$\nVuoi continuare (non consigliato)?"
LangString CloseRunningInstances ${LANG_ITALIAN} "Chiusura istanze aperte..."
LangString ShortcutHistory ${LANG_ITALIAN} "Cronologia versioni programma"
LangString ShortcutLicense ${LANG_ITALIAN} "Licenza programma"
LangString ShortcutReadme ${LANG_ITALIAN} "Visualizza Readme"
LangString ShortcutUninstall ${LANG_ITALIAN} "Disinstalla ${APP_NAME}"

LangString RequireWindows7 ${LANG_SPANISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_SPANISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_SPANISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_SPANISH} "Localization"
LangString CreateDesktopShortcut ${LANG_SPANISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_SPANISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_SPANISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_SPANISH} "Show release notes"
LangString AppUninstall ${LANG_SPANISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_SPANISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_SPANISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_SPANISH} "Close running instances..."
LangString ShortcutHistory ${LANG_SPANISH} "History"
LangString ShortcutLicense ${LANG_SPANISH} "License"
LangString ShortcutReadme ${LANG_SPANISH} "Readme"
LangString ShortcutUninstall ${LANG_SPANISH} "Uninstall"

LangString RequireWindows7 ${LANG_ARABIC} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_ARABIC} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_ARABIC} "Core files ${APP_NAME}"
LangString Localization ${LANG_ARABIC} "Localization"
LangString CreateDesktopShortcut ${LANG_ARABIC} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_ARABIC} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_ARABIC} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_ARABIC} "Show release notes"
LangString AppUninstall ${LANG_ARABIC} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_ARABIC} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_ARABIC} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_ARABIC} "Close running instances..."
LangString ShortcutHistory ${LANG_ARABIC} "History"
LangString ShortcutLicense ${LANG_ARABIC} "License"
LangString ShortcutReadme ${LANG_ARABIC} "Readme"
LangString ShortcutUninstall ${LANG_ARABIC} "Uninstall"

LangString RequireWindows7 ${LANG_ALBANIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_ALBANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_ALBANIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_ALBANIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_ALBANIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_ALBANIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_ALBANIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_ALBANIAN} "Show release notes"
LangString AppUninstall ${LANG_ALBANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_ALBANIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_ALBANIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_ALBANIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_ALBANIAN} "History"
LangString ShortcutLicense ${LANG_ALBANIAN} "License"
LangString ShortcutReadme ${LANG_ALBANIAN} "Readme"
LangString ShortcutUninstall ${LANG_ALBANIAN} "Uninstall"

LangString RequireWindows7 ${LANG_BELARUSIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_BELARUSIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_BELARUSIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_BELARUSIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_BELARUSIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_BELARUSIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_BELARUSIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_BELARUSIAN} "Show release notes"
LangString AppUninstall ${LANG_BELARUSIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_BELARUSIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_BELARUSIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_BELARUSIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_BELARUSIAN} "History"
LangString ShortcutLicense ${LANG_BELARUSIAN} "License"
LangString ShortcutReadme ${LANG_BELARUSIAN} "Readme"
LangString ShortcutUninstall ${LANG_BELARUSIAN} "Uninstall"

LangString RequireWindows7 ${LANG_CATALAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_CATALAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_CATALAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_CATALAN} "Localization"
LangString CreateDesktopShortcut ${LANG_CATALAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_CATALAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_CATALAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_CATALAN} "Show release notes"
LangString AppUninstall ${LANG_CATALAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_CATALAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_CATALAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_CATALAN} "Close running instances..."
LangString ShortcutHistory ${LANG_CATALAN} "History"
LangString ShortcutLicense ${LANG_CATALAN} "License"
LangString ShortcutReadme ${LANG_CATALAN} "Readme"
LangString ShortcutUninstall ${LANG_CATALAN} "Uninstall"

LangString RequireWindows7 ${LANG_CROATIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_CROATIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_CROATIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_CROATIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_CROATIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_CROATIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_CROATIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_CROATIAN} "Show release notes"
LangString AppUninstall ${LANG_CROATIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_CROATIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_CROATIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_CROATIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_CROATIAN} "History"
LangString ShortcutLicense ${LANG_CROATIAN} "License"
LangString ShortcutReadme ${LANG_CROATIAN} "Readme"
LangString ShortcutUninstall ${LANG_CROATIAN} "Uninstall"

LangString RequireWindows7 ${LANG_CZECH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_CZECH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_CZECH} "Core files ${APP_NAME}"
LangString Localization ${LANG_CZECH} "Localization"
LangString CreateDesktopShortcut ${LANG_CZECH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_CZECH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_CZECH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_CZECH} "Show release notes"
LangString AppUninstall ${LANG_CZECH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_CZECH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_CZECH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_CZECH} "Close running instances..."
LangString ShortcutHistory ${LANG_CZECH} "History"
LangString ShortcutLicense ${LANG_CZECH} "License"
LangString ShortcutReadme ${LANG_CZECH} "Readme"
LangString ShortcutUninstall ${LANG_CZECH} "Uninstall"

LangString RequireWindows7 ${LANG_DANISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_DANISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_DANISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_DANISH} "Localization"
LangString CreateDesktopShortcut ${LANG_DANISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_DANISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_DANISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_DANISH} "Show release notes"
LangString AppUninstall ${LANG_DANISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_DANISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_DANISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_DANISH} "Close running instances..."
LangString ShortcutHistory ${LANG_DANISH} "History"
LangString ShortcutLicense ${LANG_DANISH} "License"
LangString ShortcutReadme ${LANG_DANISH} "Readme"
LangString ShortcutUninstall ${LANG_DANISH} "Uninstall"

LangString RequireWindows7 ${LANG_DUTCH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_DUTCH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_DUTCH} "Core files ${APP_NAME}"
LangString Localization ${LANG_DUTCH} "Localization"
LangString CreateDesktopShortcut ${LANG_DUTCH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_DUTCH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_DUTCH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_DUTCH} "Show release notes"
LangString AppUninstall ${LANG_DUTCH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_DUTCH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_DUTCH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_DUTCH} "Close running instances..."
LangString ShortcutHistory ${LANG_DUTCH} "History"
LangString ShortcutLicense ${LANG_DUTCH} "License"
LangString ShortcutReadme ${LANG_DUTCH} "Readme"
LangString ShortcutUninstall ${LANG_DUTCH} "Uninstall"

LangString RequireWindows7 ${LANG_FARSI} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_FARSI} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_FARSI} "Core files ${APP_NAME}"
LangString Localization ${LANG_FARSI} "Localization"
LangString CreateDesktopShortcut ${LANG_FARSI} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_FARSI} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_FARSI} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_FARSI} "Show release notes"
LangString AppUninstall ${LANG_FARSI} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_FARSI} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_FARSI} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_FARSI} "Close running instances..."
LangString ShortcutHistory ${LANG_FARSI} "History"
LangString ShortcutLicense ${LANG_FARSI} "License"
LangString ShortcutReadme ${LANG_FARSI} "Readme"
LangString ShortcutUninstall ${LANG_FARSI} "Uninstall"

LangString RequireWindows7 ${LANG_GREEK} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_GREEK} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_GREEK} "Core files ${APP_NAME}"
LangString Localization ${LANG_GREEK} "Localization"
LangString CreateDesktopShortcut ${LANG_GREEK} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_GREEK} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_GREEK} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_GREEK} "Show release notes"
LangString AppUninstall ${LANG_GREEK} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_GREEK} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_GREEK} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_GREEK} "Close running instances..."
LangString ShortcutHistory ${LANG_GREEK} "History"
LangString ShortcutLicense ${LANG_GREEK} "License"
LangString ShortcutReadme ${LANG_GREEK} "Readme"
LangString ShortcutUninstall ${LANG_GREEK} "Uninstall"

LangString RequireWindows7 ${LANG_KOREAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_KOREAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_KOREAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_KOREAN} "Localization"
LangString CreateDesktopShortcut ${LANG_KOREAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_KOREAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_KOREAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_KOREAN} "Show release notes"
LangString AppUninstall ${LANG_KOREAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_KOREAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_KOREAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_KOREAN} "Close running instances..."
LangString ShortcutHistory ${LANG_KOREAN} "History"
LangString ShortcutLicense ${LANG_KOREAN} "License"
LangString ShortcutReadme ${LANG_KOREAN} "Readme"
LangString ShortcutUninstall ${LANG_KOREAN} "Uninstall"

LangString RequireWindows7 ${LANG_HUNGARIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_HUNGARIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_HUNGARIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_HUNGARIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_HUNGARIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_HUNGARIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_HUNGARIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_HUNGARIAN} "Show release notes"
LangString AppUninstall ${LANG_HUNGARIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_HUNGARIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_HUNGARIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_HUNGARIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_HUNGARIAN} "History"
LangString ShortcutLicense ${LANG_HUNGARIAN} "License"
LangString ShortcutReadme ${LANG_HUNGARIAN} "Readme"
LangString ShortcutUninstall ${LANG_HUNGARIAN} "Uninstall"

LangString RequireWindows7 ${LANG_INDONESIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_INDONESIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_INDONESIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_INDONESIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_INDONESIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_INDONESIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_INDONESIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_INDONESIAN} "Show release notes"
LangString AppUninstall ${LANG_INDONESIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_INDONESIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_INDONESIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_INDONESIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_INDONESIAN} "History"
LangString ShortcutLicense ${LANG_INDONESIAN} "License"
LangString ShortcutReadme ${LANG_INDONESIAN} "Readme"
LangString ShortcutUninstall ${LANG_INDONESIAN} "Uninstall"

LangString RequireWindows7 ${LANG_JAPANESE} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_JAPANESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_JAPANESE} "Core files ${APP_NAME}"
LangString Localization ${LANG_JAPANESE} "Localization"
LangString CreateDesktopShortcut ${LANG_JAPANESE} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_JAPANESE} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_JAPANESE} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_JAPANESE} "Show release notes"
LangString AppUninstall ${LANG_JAPANESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_JAPANESE} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_JAPANESE} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_JAPANESE} "Close running instances..."
LangString ShortcutHistory ${LANG_JAPANESE} "History"
LangString ShortcutLicense ${LANG_JAPANESE} "License"
LangString ShortcutReadme ${LANG_JAPANESE} "Readme"
LangString ShortcutUninstall ${LANG_JAPANESE} "Uninstall"

LangString RequireWindows7 ${LANG_LITHUANIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_LITHUANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_LITHUANIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_LITHUANIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_LITHUANIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_LITHUANIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_LITHUANIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_LITHUANIAN} "Show release notes"
LangString AppUninstall ${LANG_LITHUANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_LITHUANIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_LITHUANIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_LITHUANIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_LITHUANIAN} "History"
LangString ShortcutLicense ${LANG_LITHUANIAN} "License"
LangString ShortcutReadme ${LANG_LITHUANIAN} "Readme"
LangString ShortcutUninstall ${LANG_LITHUANIAN} "Uninstall"

LangString RequireWindows7 ${LANG_POLISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_POLISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_POLISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_POLISH} "Localization"
LangString CreateDesktopShortcut ${LANG_POLISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_POLISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_POLISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_POLISH} "Show release notes"
LangString AppUninstall ${LANG_POLISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_POLISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_POLISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_POLISH} "Close running instances..."
LangString ShortcutHistory ${LANG_POLISH} "History"
LangString ShortcutLicense ${LANG_POLISH} "License"
LangString ShortcutReadme ${LANG_POLISH} "Readme"
LangString ShortcutUninstall ${LANG_POLISH} "Uninstall"

LangString RequireWindows7 ${LANG_PORTUGUESE} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_PORTUGUESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_PORTUGUESE} "Core files ${APP_NAME}"
LangString Localization ${LANG_PORTUGUESE} "Localization"
LangString CreateDesktopShortcut ${LANG_PORTUGUESE} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_PORTUGUESE} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_PORTUGUESE} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_PORTUGUESE} "Show release notes"
LangString AppUninstall ${LANG_PORTUGUESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_PORTUGUESE} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_PORTUGUESE} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_PORTUGUESE} "Close running instances..."
LangString ShortcutHistory ${LANG_PORTUGUESE} "History"
LangString ShortcutLicense ${LANG_PORTUGUESE} "License"
LangString ShortcutReadme ${LANG_PORTUGUESE} "Readme"
LangString ShortcutUninstall ${LANG_PORTUGUESE} "Uninstall"

LangString RequireWindows7 ${LANG_PORTUGUESEBR} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_PORTUGUESEBR} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_PORTUGUESEBR} "Core files ${APP_NAME}"
LangString Localization ${LANG_PORTUGUESEBR} "Localization"
LangString CreateDesktopShortcut ${LANG_PORTUGUESEBR} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_PORTUGUESEBR} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_PORTUGUESEBR} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_PORTUGUESEBR} "Show release notes"
LangString AppUninstall ${LANG_PORTUGUESEBR} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_PORTUGUESEBR} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_PORTUGUESEBR} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_PORTUGUESEBR} "Close running instances..."
LangString ShortcutHistory ${LANG_PORTUGUESEBR} "History"
LangString ShortcutLicense ${LANG_PORTUGUESEBR} "License"
LangString ShortcutReadme ${LANG_PORTUGUESEBR} "Readme"
LangString ShortcutUninstall ${LANG_PORTUGUESEBR} "Uninstall"

LangString RequireWindows7 ${LANG_ROMANIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_ROMANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_ROMANIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_ROMANIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_ROMANIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_ROMANIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_ROMANIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_ROMANIAN} "Show release notes"
LangString AppUninstall ${LANG_ROMANIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_ROMANIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_ROMANIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_ROMANIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_ROMANIAN} "History"
LangString ShortcutLicense ${LANG_ROMANIAN} "License"
LangString ShortcutReadme ${LANG_ROMANIAN} "Readme"
LangString ShortcutUninstall ${LANG_ROMANIAN} "Uninstall"

LangString RequireWindows7 ${LANG_RUSSIAN} "${APP_NAME} необходим Windows 7 и выше!"
LangString UninstallAp ${LANG_RUSSIAN} "Удалить ${APP_NAME}?"
LangString CoreFiles ${LANG_RUSSIAN} "${APP_NAME}"
LangString Localization ${LANG_RUSSIAN} "Локализация"
LangString CreateDesktopShortcut ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
LangString CreateStartMenuShortcut ${LANG_RUSSIAN} "Создать ярлык в меню пуск"
LangString StoreSettingsApplicationDir ${LANG_RUSSIAN} "Хранить настройки в папке программы (портативный режим)"
LangString ShowReleaseNote ${LANG_RUSSIAN} "Показать список изменений"
LangString AppUninstall ${LANG_RUSSIAN} "Удалить ${APP_NAME}?"
LangString AppRemoved ${LANG_RUSSIAN} "${APP_NAME} успешно удалён!"
LangString AppFolderNotCheck ${LANG_RUSSIAN} "Не похоже на то что ${APP_NAME} установлен.$\r$\nПродолжить (не рекомендуется)?"
LangString CloseRunningInstances ${LANG_RUSSIAN} "Закрытие запущенных программ..."
LangString ShortcutHistory ${LANG_RUSSIAN} "История"
LangString ShortcutLicense ${LANG_RUSSIAN} "Лицензия"
LangString ShortcutReadme ${LANG_RUSSIAN} "Readme"
LangString ShortcutUninstall ${LANG_RUSSIAN} "Uninstall"

LangString RequireWindows7 ${LANG_SIMPCHINESE} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_SIMPCHINESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_SIMPCHINESE} "Core files ${APP_NAME}"
LangString Localization ${LANG_SIMPCHINESE} "Localization"
LangString CreateDesktopShortcut ${LANG_SIMPCHINESE} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_SIMPCHINESE} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_SIMPCHINESE} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_SIMPCHINESE} "Show release notes"
LangString AppUninstall ${LANG_SIMPCHINESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_SIMPCHINESE} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_SIMPCHINESE} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_SIMPCHINESE} "Close running instances..."
LangString ShortcutHistory ${LANG_SIMPCHINESE} "History"
LangString ShortcutLicense ${LANG_SIMPCHINESE} "License"
LangString ShortcutReadme ${LANG_SIMPCHINESE} "Readme"
LangString ShortcutUninstall ${LANG_SIMPCHINESE} "Uninstall"

LangString RequireWindows7 ${LANG_SWEDISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_SWEDISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_SWEDISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_SWEDISH} "Localization"
LangString CreateDesktopShortcut ${LANG_SWEDISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_SWEDISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_SWEDISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_SWEDISH} "Show release notes"
LangString AppUninstall ${LANG_SWEDISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_SWEDISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_SWEDISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_SWEDISH} "Close running instances..."
LangString ShortcutHistory ${LANG_SWEDISH} "History"
LangString ShortcutLicense ${LANG_SWEDISH} "License"
LangString ShortcutReadme ${LANG_SWEDISH} "Readme"
LangString ShortcutUninstall ${LANG_SWEDISH} "Uninstall"

LangString RequireWindows7 ${LANG_THAI} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_THAI} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_THAI} "Core files ${APP_NAME}"
LangString Localization ${LANG_THAI} "Localization"
LangString CreateDesktopShortcut ${LANG_THAI} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_THAI} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_THAI} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_THAI} "Show release notes"
LangString AppUninstall ${LANG_THAI} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_THAI} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_THAI} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_THAI} "Close running instances..."
LangString ShortcutHistory ${LANG_THAI} "History"
LangString ShortcutLicense ${LANG_THAI} "License"
LangString ShortcutReadme ${LANG_THAI} "Readme"
LangString ShortcutUninstall ${LANG_THAI} "Uninstall"

LangString RequireWindows7 ${LANG_TRADCHINESE} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_TRADCHINESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_TRADCHINESE} "Core files ${APP_NAME}"
LangString Localization ${LANG_TRADCHINESE} "Localization"
LangString CreateDesktopShortcut ${LANG_TRADCHINESE} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_TRADCHINESE} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_TRADCHINESE} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_TRADCHINESE} "Show release notes"
LangString AppUninstall ${LANG_TRADCHINESE} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_TRADCHINESE} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_TRADCHINESE} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_TRADCHINESE} "Close running instances..."
LangString ShortcutHistory ${LANG_TRADCHINESE} "History"
LangString ShortcutLicense ${LANG_TRADCHINESE} "License"
LangString ShortcutReadme ${LANG_TRADCHINESE} "Readme"
LangString ShortcutUninstall ${LANG_TRADCHINESE} "Uninstall"

LangString RequireWindows7 ${LANG_TURKISH} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_TURKISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_TURKISH} "Core files ${APP_NAME}"
LangString Localization ${LANG_TURKISH} "Localization"
LangString CreateDesktopShortcut ${LANG_TURKISH} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_TURKISH} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_TURKISH} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_TURKISH} "Show release notes"
LangString AppUninstall ${LANG_TURKISH} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_TURKISH} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_TURKISH} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_TURKISH} "Close running instances..."
LangString ShortcutHistory ${LANG_TURKISH} "History"
LangString ShortcutLicense ${LANG_TURKISH} "License"
LangString ShortcutReadme ${LANG_TURKISH} "Readme"
LangString ShortcutUninstall ${LANG_TURKISH} "Uninstall"

LangString RequireWindows7 ${LANG_UKRAINIAN} "${APP_NAME} requires Windows 7 and later!"
LangString UninstallAp ${LANG_UKRAINIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString CoreFiles ${LANG_UKRAINIAN} "Core files ${APP_NAME}"
LangString Localization ${LANG_UKRAINIAN} "Localization"
LangString CreateDesktopShortcut ${LANG_UKRAINIAN} "Create desktop shortcut"
LangString CreateStartMenuShortcut ${LANG_UKRAINIAN} "Create start menu shortcuts"
LangString StoreSettingsApplicationDir ${LANG_UKRAINIAN} "Store settings in application directory (portable mode)"
LangString ShowReleaseNote ${LANG_UKRAINIAN} "Show release notes"
LangString AppUninstall ${LANG_UKRAINIAN} "Are you sure you want to uninstall ${APP_NAME}?"
LangString AppRemoved ${LANG_UKRAINIAN} "${APP_NAME} was completely removed!"
LangString AppFolderNotCheck ${LANG_UKRAINIAN} "It does not appear that ${APP_NAME} is installed in the installation directory.$\r$\nContinue anyway (not recommended)?"
LangString CloseRunningInstances ${LANG_UKRAINIAN} "Close running instances..."
LangString ShortcutHistory ${LANG_UKRAINIAN} "History"
LangString ShortcutLicense ${LANG_UKRAINIAN} "License"
LangString ShortcutReadme ${LANG_UKRAINIAN} "Readme"
LangString ShortcutUninstall ${LANG_UKRAINIAN} "Uninstall"

